#!/bin/sh


#: Shell Basics {{{
alias	b="cd .."      
#alias	ls="lsd --color=auto" 
#alias l="lsd -l" 
#alias	la="lsd -a" 
#alias	lla="lsd -la"	
#alias lt="lsd --tree"
alias cp="cp -i"                                                # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB
# Date 
#alias today='date && xclip -i'
# Better Tools
alias ping="prettyping"
#Places
alias dot="cd /home/niko/.dot-tales"

#: }}}

#: System Administration {{{

# SystemWide
alias ip='ip -color=auto'
alias date2="date '+%F'" 
alias mem="cat /proc/meminfo"
# Screen
alias screenoff='xset dpms force off && i3lock-fancy-dualmonitor'
# Restic 
alias rest-backup='restic backup --files-from /home/niko/.restic_include.txt'
alias rest-snap='restic snapshots'
alias rest-clean='restic cache --cleanup'
alias rest-prune='restic forget --keep-last 1 --prune'
	
# Vim
alias lv="/home/niko/.local/bin/lvim"
alias	vm="nvim"  
# bpytop
alias status="bpytop"
# Pacman
alias pau="pacui 3"
alias update="sudo paru -Syu"	
# source
alias svim="source ~/.dot-tales/neovim/.config/nvim/init.vim"
alias szsh="source ~/.zshrc"
alias stmux="source ~/.tmux.conf"
alias atmux="tmux new-session -A -s Main"
#	Font Refresh	
alias fonts="fc-cache -f -v"

# Mount
alias sdc="sudo mount /dev/sdc ~/Usb -o uid=niko -o gid=niko"
#alias sdb="sudo mount /dev/sdb2 /home/niko/Hdd -o uid=niko -o gid=niko"
alias sdb="sudo mount /dev/sdb2 /home/niko/Hdd"

#: }}}

#: Tools {{{
# Grep
alias grep="grep --color=auto" 
# Curl ( Real time execution )
alias	tiempo="curl wttr.in" 
# Wallpaper fzfScript
alias wall="ls /run/media/hdd/Pictures/wall/* | fzfimg --bind 'enter:execute-silent(feh --bg-scale {} && cp {} ~/.config/wall.png )'" 
# simple-mtpfs ( Android Mounting)
alias android="simple-mtpfs --device 1 /home/niko/Storage/Cell/"
# npm list all packages
alias npmlist="npm list -g --depth=0"
# copy with progress details
alias copy="rsync -avh --progress"
# get keyboard key
alias keys="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'\n"
#: }}}

#: Apps {{{

#	Firefox
alias fire="firefox -p niko </dev/null &>/dev/null &"
# Tmux
alias	tm="tmux new-session -A -s Main" 
# Kitty vim server 
alias kv="kitty --class vimpad -e nvim </dev/null &>/dev/null &"
# Dropdown  
alias drop="kitty --class dropdown </dev/null &>/dev/null &"
# tg
alias ftg="kitty --class social -e tg </dev/null &>/dev/null &"

# NCDU ( Ncurses disk space analizer )
alias	disk="ncdu" 
# Mutt Wizard
alias syncmail="mw -Y"
# TUIR ( Reddit Ncurses)	
alias	reddit="tuir" 
# TaskWarrior
# entr + taskwarrior commands
alias tc=" ls .task/* | entr task calendar"
alias tb=" ls .task/* | entr task burndown.weekly"
alias	tsummary="ls .task/* | entr task summary" 
alias ta="ls .task/*.data | entr task +ACTIVE"
alias	t="task" 
alias	tl="task +LATEST" 
alias	tnw="task newest" 
alias tw='task rc.defaultwidth=0 rc.defaultheight=0 rc.verbose=nothing rc._forcecolor=on'
# PipeViewer
alias pipe="pipe-viewer --use-colors --get-term-width"
alias pipech="pipe-viewer --use-colors -sc"
# Pass
alias passgen="pass generate -c"
alias pc="pass --clip"
alias dot-tales="pass --clip github.dot-tales"

# ncmpcpp
alias music="ncmpcpp"
# Mind mapping
alias mind="mm /run/media/hdd/Documents/mindmaps/lifeOn2021"
# nb Bash Note Taking
#alias nb="bash /home/niko/.npm-global/bin/nb shell"
#	tmux
alias clock="tmux clock-mode"

# Kitty Themes
alias kt="kitty +kitten themes"

# Nvim
alias vim="nvim"

#: }}}	

#: Places {{{

alias hdd="cd /run/media/hdd"
alias	books="/run/media/hdd/Books/"
alias fbooks="ls * /run/media/hdd/Books/ | fzf"
alias usb="cd /run/media/usb"
alias dwn="cd /home/niko/Downloads"
alias gdrive="rclone mount --daemon drive: /home/niko/Gdrive"
alias	yt="pipe-viewer"
alias holberton='sshpass -p "$(pass show holbert.server)" ssh root@54.242.22.52'
# New Server
alias fresh-server='echo "touch freshRun.sh && curl -L https://raw.githubusercontent.com/pegromdev/.dot-tales/main/server/serverFirstRun.sh >> freshRun.sh" | xclip -sel clip'
	
alias lock="i3lock-fancy"
alias batalias="bat ~/.config/aliasrc"
#: }}}
